### PR TITLE
fix: ALL implicit privileges equality check

### LINKED ISSUE #32: Allow ALL privilegies for postgresql_grant
Hi

It will be good if  postgresql_grant resource will allow ALL in addition to others like

privileges - (Required) The list of privileges to grant. There are different kinds of privileges: SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, CREATE, CONNECT, TEMPORARY, EXECUTE, and USAGE.

as per 

GRANT { { CREATE | USAGE } [,...] | **ALL** [ PRIVILEGES ] }
    ON SCHEMA schema_name [, ...]
    TO { [ GROUP ] role_name | PUBLIC } [, ...] [ WITH GRANT OPTION ]

### PR DESCRIPTION
**Pull request by talbx**
When using resources `postgresql_default_privileges` or `postgresql_grant` you have the option to define a fine grained set of privileges (for example only `CONNECT` for object_type `database`) or all at once, either by setting all privileges (for database: `["CREATE", "CONNECT", "TEMPORARY"]` or simply `["ALL"]`.

The latter one is quite handy, since you do not have to find out which privileges are part of it. When using `ALL`, the provider will grant the privileges by using the set of the actual grants,  so in this scenario by granting `"CREATE", "CONNECT", "TEMPORARY"` and not `ALL`. Probably because `ALL` is not known to postgres. 🤷🏼‍♂️ 

Anyways, when executing a `terraform plan` the next time after the apply for `ALL`, the diff will find out, that not `ALL` is set as privilege, but `"CREATE", "CONNECT", "TEMPORARY"`. Since these privileges are the same or have the same semantic to it, there shouldn't be really a update each time you use terraform, because the state on the DB is totally fine and according to the resource.

To prevent this unnecessary modification, I implemented some more detailed equality check for all `object_type`s except `column`. 

I tested the changes locally with a dockerized postgres and also wrote some unit tests for it.

Would love to hear some feedback about it, especially since it's my first time working on a terraform provider.. 

Cheers

fix #32

### CODE REVIEW

**Comment by talbx** [comment]
@cyrilgdn any chance you can take a look at that?

File: postgresql/helpers.go [hunk 1]
```diff
@@ -267,6 +267,34 @@ func validatePrivileges(d *schema.ResourceData) error {
 	return nil
 }
 
+func arePrivilegesEqual(granted *schema.Set, wanted *schema.Set, d *schema.ResourceData) bool {
```
Comment (cyrilgdn) [inline postgresql/helpers.go:270]: You seem to all read `wanted` from `d` that you also pass as function arguments, so I guess you could pass `d` only?

```suggestion
func resourcePrivilegesEqual(granted *schema.Set, d *schema.ResourceData) bool {
  wanted := d.Get("privileges").(*schema.Set)
```

File: postgresql/resource_postgresql_grant.go [hunk 2]
```diff
@@ -108,7 +108,9 @@ func resourcePostgreSQLGrantRead(db *DBConnection, d *schema.ResourceData) error
 	if err := validateFeatureSupport(db, d); err != nil {
 		return fmt.Errorf("feature is not supported: %v", err)
 	}
-
+	if true {
+		//return fmt.Errorf("hello world! %v", "you")
+	}
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:113]:
```suggestion
```

File: postgresql/resource_postgresql_grant.go [hunk 3]
```diff
@@ -269,8 +271,12 @@ WHERE grantee = $2
 	if err := txn.QueryRow(query, dbName, roleOID).Scan(&privileges); err != nil {
 		return fmt.Errorf("could not read privileges for database %s: %w", dbName, err)
 	}
-
-	d.Set("privileges", pgArrayToSet(privileges))
+	granted := pgArrayToSet(privileges)
+	wanted := d.Get("privileges").(*schema.Set)
+	equal := arePrivilegesEqual(granted, wanted, d)
+	if !equal {
+		return d.Set("privileges", wanted)
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:278]: `granted` no ? as this function read the state of the database. Otherwise there will never be any diff as you set in the state what's in the state already.
```suggestion
		return d.Set("privileges", granted)
```

File: postgresql/resource_postgresql_grant.go [hunk 4]
```diff
@@ -289,7 +295,12 @@ WHERE grantee = $2
 		return fmt.Errorf("could not read privileges for schema %s: %w", dbName, err)
 	}
 
-	d.Set("privileges", pgArrayToSet(privileges))
+	granted := pgArrayToSet(privileges)
+	wanted := d.Get("privileges").(*schema.Set)
+	equal := arePrivilegesEqual(granted, wanted, d)
+	if !equal {
+		return d.Set("privileges", wanted)
+	}
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:303]: In addition to the comment above about `wanted`/`granted`, for all these calls, the `equal` variable could be removed, and if we take into account my first comment about the function argument, it could look like:

```suggestion
	if !resourcePrivilegesEqual(granted, d)
		return d.Set("privileges", granted)
	}
```

File: postgresql/resource_postgresql_grant.go [hunk 5]
```diff
@@ -415,6 +436,9 @@ func readRolePrivileges(txn *sql.Tx, d *schema.ResourceData) error {
 	role := d.Get("role").(string)
 	objectType := d.Get("object_type").(string)
 	objects := d.Get("objects").(*schema.Set)
+	for _, entry := range objects.List() {
+		log.Printf("this is a entry: %v", entry)
+	}
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:441]: Debugging?

```suggestion
```

File: postgresql/resource_postgresql_grant.go [hunk 6]
```diff
@@ -502,8 +526,8 @@ GROUP BY pg_class.relname
 		}
 
 		privilegesSet := pgArrayToSet(privileges)
-
-		if !privilegesSet.Equal(d.Get("privileges").(*schema.Set)) {
+		privilegesEqual := arePrivilegesEqual(privilegesSet, d.Get("privileges").(*schema.Set), d)
+		if !privilegesEqual {
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:530]:
```suggestion
		if !resourcePrivilegesEqual(privilegesSet, d)
```

**Review by cyrilgdn — CHANGES_REQUESTED** [review]
Hi @talbx,

Thanks for opening this PR and many apologies for the response delay, I didn't have the time to work on this provider.

I like the idea :+1: , it's a simple solution to fix this very old bug. I still need to test what you did though, cf my comment about `wanted` / `granted` when you set the value, I'm not sure it works like that.

Thanks for the unittest on the new function :+1:  
It would be nice to also have acceptance test about that on `postgresql_grant` resource, there's already many tests in `postgresql_grant_test.go`
You can have a look at this one for example: https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_grant_test.go#L1082-L1140

but let me know if you need help or if you don't have time, I can have a look.

File: postgresql/helpers.go (hunk 1 above)
Comment (talbx) [reply postgresql/helpers.go]: changed with 8dfcf905d1bfb5746001a6e98fca82492058bb1b

File: postgresql/resource_postgresql_grant.go (hunk 3 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go:275]: I am not quite sure about that. We check whats on the DB...

 if the state on the DB does not equal whats requested via terraform, we want to set the privileges that are requested. `granted` is what we already have.

File: postgresql/resource_postgresql_grant.go (hunk 4 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go]: inlined the if statement with 8dfcf905d1bfb5746001a6e98fca82492058bb1b

File: postgresql/resource_postgresql_grant.go (hunk 6 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go]: inlined every other equality check with [db54bfc](https://github.com/cyrilgdn/terraform-provider-postgresql/pull/339/commits/db54bfcdf27549a299b2bf23a7e2f58e747d75b8)

File: postgresql/resource_postgresql_grant.go (hunk 2 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go]: removed with [8dfcf90](https://github.com/cyrilgdn/terraform-provider-postgresql/pull/339/commits/8dfcf905d1bfb5746001a6e98fca82492058bb1b)

File: postgresql/resource_postgresql_grant.go (hunk 3 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go:274]: the only thing that is weird to me right now is the fact, that I fetch the required privileges from the resourcedata and then put it back there again. this call is quite superflous but still won't hurt.

**Comment by talbx** [comment]
> Thanks for opening this PR and many apologies for the response delay, I didn't have the time to work on this provider.

no worries, thanks for checking in again :)


> Thanks for the unittest on the new function 👍 It would be nice to also have acceptance test about that on `postgresql_grant` resource, there's already many tests in `postgresql_grant_test.go` You can have a look at this one for example: https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_grant_test.go#L1082-L1140

I will give it a shot.

File: postgresql/resource_postgresql_grant.go (hunk 3 above)
Comment (cyrilgdn) [reply postgresql/resource_postgresql_grant.go:274]: > we want to set the privileges that are requested. granted is what we already have.

Indeed, but that's not exactly how this function works.

The goal of a resource read function (in this case `resourcePostgreSQLGrantRead`) is to refresh the Terraform state with the current status of what's in Postgres. 

Then Terraform will compare the resource as it's defined in your code with how it is in the state (so in Postgres).
So the goal of this line is to set the privileges as it is in the dabase so it will be compared with what's defined in you resource definition.

> Since i tested the changes with a database locally and had great success with the former implementation

It's because you haven't tested all the use cases (if I dare :sweat_smile: )

You think you fully fix that because there's no more diff in `terraform plan` compared to before, but actually there will now never be any diff because you say that the current state in the database is what's defined in your code, so Terraform will always say that everything is already correct.

Easy to demonstrate with this simple code:

```hcl
resource "postgresql_database" "test" { 
  name = "test_db"
}

resource "postgresql_role" "test" {
  name = "test"
}

resource "postgresql_grant" "db_all" {
  database    = postgresql_database.test.name
  role        = postgresql_role.test.name
  object_type = "database"
  privileges  = ["ALL"]
}
```
that you can apply:
```
terraform apply
```

Then, you manually remove a permission in Postgres:
```
$ psql -c "revoke connect ON database test_db from test "
REVOKE
```

And next `terraform plan` will not show any diff when it should say that it needs to fix the permissions.


If I rebuild my provider with the suggestion I did above (set `granted` instead of wanted), if I manually remove a permission from the database, I will have this plan:

```
$ terraform plan
[...]
Terraform will perform the following actions:

  # postgresql_grant.db_all must be replaced
-/+ resource "postgresql_grant" "db_all" {
      ~ id                = "test_test_db_database" -> (known after apply)
      ~ privileges        = [ # forces replacement
          - "CREATE",
          - "TEMPORARY",
          + "ALL",
        ]
        # (4 unchanged attributes hidden)
    }
```
And once applied, thanks to your fix, there will not be any diff in the next plan.

**Review by cyrilgdn — CHANGES_REQUESTED** [review]
cf my answer here: https://github.com/cyrilgdn/terraform-provider-postgresql/pull/339#discussion_r1509980448

File: postgresql/resource_postgresql_grant.go (hunk 3 above)
Comment (talbx) [reply postgresql/resource_postgresql_grant.go]: .. that sounds reasonable 😅 i adjusted that with [54fc593](https://github.com/cyrilgdn/terraform-provider-postgresql/pull/339/commits/54fc593f610136ed3d41b95dbe9f826de0a49bf6) and provided an acceptance test for it. would be cool if you could check again @cyrilgdn 

thanks in advance

**Comment by talbx** [comment]
might relate to #303

**Comment by dzavalkin-scayle** [comment]
Any chance this PR will be merged soon @cyrilgdn @talbx 🙏 ? We are tired seeing perpetual diff in all places where we use `postgresql_grant` resource...

**Comment by talbx** [comment]
> Any chance this PR will be merged soon @cyrilgdn @talbx 🙏 ? We are tired seeing perpetual diff in all places where we use `postgresql_grant` resource...

I am still waiting for further feedback by @cyrilgdn; although i am not sure it will resolve your problems, @dzavalkin-scayle  since you haven't specified them in detail and also, this PR solely focusses on the implicit "ALL" diff. I haven't tested, if this PR fixes other cases aswell.

**Comment by dzavalkin-scayle** [comment]
> i am not sure it will resolve your problems, @dzavalkin-scayle since you haven't specified them in detail and also, this PR solely focusses on the implicit "ALL" diff. I haven't tested, if this PR fixes other cases aswell.

Hmm I was under impression that it will fix diff issue entirely, no matter what are the privileges...
Without this fix we need to add privileges to `ignore_changes` which isn't nice at all and raises a question if we should look for another `postgresql` provider then 😞

**Comment by talbx** [comment]
> > i am not sure it will resolve your problems, @dzavalkin-scayle since you haven't specified them in detail and also, this PR solely focusses on the implicit "ALL" diff. I haven't tested, if this PR fixes other cases aswell.
> 
> Hmm I was under impression that it will fix diff issue entirely, no matter what are the privileges... Without this fix we need to add privileges to `ignore_changes` which isn't nice at all and raises a question if we should look for another `postgresql` provider then 😞

@dzavalkin-scayle can you give me a Terraform snippet to reproduce your problem? i can recheck if its included

**Comment by dzavalkin-scayle** [comment]
@talbx Thanks a lot! Here is the code we have:

```hcl
locals {
  default_privileges = merge([
    for owner, users in var.rds_postgres_user_default_privileges :
    {
      for user in users : "${owner}-${user}" => {
        owner = owner
        user  = user
      }
    }
  ]...)
}

resource "random_password" "user_password" {
  for_each = { for k, v in var.rds_postgres_users : k => v if !lookup(v, "allow_iam_role_access", false) }

  length = 42

  special = true
  numeric = true
  lower   = true
  upper   = true

  override_special = "!()-_=[]{}"
  min_numeric      = 3
  min_lower        = 3
  min_upper        = 3
}

resource "postgresql_role" "postgres_users" {
  for_each = var.rds_postgres_users

  name     = each.key
  login    = true
  password = lookup(each.value, "allow_iam_role_access", false) ? "" : random_password.user_password[each.key].result
  roles    = lookup(each.value, "allow_iam_role_access", false) ? ["rds_iam"] : []
}

resource "postgresql_default_privileges" "postgresql_user_default_table_privileges" {
  for_each = {
    for key, value in local.default_privileges :
    key => value
    if lookup(var.rds_postgres_users[value.user], "table_privileges", "") != ""
  }

  database    = var.rds_database_name
  object_type = "table"
  owner       = each.value.owner
  privileges  = split(",", var.rds_postgres_users[each.value.user].table_privileges)
  role        = each.value.user
  schema      = "public"

  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_default_privileges" "postgresql_user_default_sequence_privileges" {
  for_each = {
    for key, value in local.default_privileges :
    key => value
    if lookup(var.rds_postgres_users[value.user], "sequence_privileges", "") != ""
  }

  database    = var.rds_database_name
  object_type = "sequence"
  owner       = each.value.owner
  privileges  = split(",", var.rds_postgres_users[each.value.user].sequence_privileges)
  role        = each.value.user
  schema      = "public"

  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_default_privileges" "postgresql_user_default_routine_privileges" {
  for_each = {
    for key, value in local.default_privileges :
    key => value
    if lookup(var.rds_postgres_users[value.user], "routine_privileges", "") != ""
  }

  database    = var.rds_database_name
  object_type = "function"
  owner       = each.value.owner
  privileges  = split(",", var.rds_postgres_users[each.value.user].routine_privileges)
  role        = each.value.user
  schema      = "public"

  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_grant" "postgresql_user_table_privileges" {
  for_each = {
    for username, user_settings in var.rds_postgres_users :
    username => user_settings
    if lookup(user_settings, "table_privileges", "") != ""
  }

  database          = var.rds_database_name
  object_type       = "table"
  privileges        = split(",", each.value.table_privileges)
  role              = each.key
  schema            = "public"
  with_grant_option = lookup(each.value, "grant", false)
  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_grant" "postgresql_user_database_privileges" {
  for_each = {
    for username, user_settings in var.rds_postgres_users :
    username => user_settings
    if lookup(user_settings, "database_privileges", "") != ""
  }

  database          = var.rds_database_name
  object_type       = "database"
  privileges        = split(",", each.value.database_privileges)
  role              = each.key
  with_grant_option = lookup(each.value, "grant", false)
  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_grant" "postgresql_user_routine_privileges" {
  for_each = {
    for username, user_settings in var.rds_postgres_users :
    username => user_settings
    if lookup(user_settings, "routine_privileges", "") != ""
  }

  database          = var.rds_database_name
  role              = each.key
  object_type       = "routine"
  schema            = "public"
  privileges        = split(",", each.value["routine_privileges"])
  with_grant_option = lookup(each.value, "grant", false)
  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_grant" "postgresql_user_schema_privileges" {
  for_each = {
    for username, user_settings in var.rds_postgres_users :
    username => user_settings
    if lookup(user_settings, "schema_privileges", "") != ""
  }

  database          = var.rds_database_name
  object_type       = "schema"
  privileges        = split(",", each.value["schema_privileges"])
  role              = each.key
  schema            = "public"
  with_grant_option = lookup(each.value, "grant", false)
  depends_on = [
    postgresql_role.postgres_users
  ]
}

resource "postgresql_grant" "postgresql_user_sequence_privileges" {
  for_each = {
    for username, user_settings in var.rds_postgres_users :
    username => user_settings
    if lookup(user_settings, "sequence_privileges", "") != ""
  }

  database          = var.rds_database_name
  role              = each.key
  object_type       = "sequence"
  schema            = "public"
  privileges        = split(",", each.value["sequence_privileges"])
  with_grant_option = lookup(each.value, "grant", false)
  depends_on = [
    postgresql_role.postgres_users
  ]
}
```

and values for input variables are (passed from Terragrunt):

```hcl
  rds_postgres_users = {
    app_schema = {
      database_privileges = "CONNECT"
      grant               = true
      schema_privileges   = "CREATE,USAGE"
      routine_privileges  = "EXECUTE"
      sequence_privileges = "SELECT,UPDATE"
      table_privileges    = "SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER"
    },
    app_unrestricted = {
      database_privileges = "CONNECT"
      routine_privileges  = "EXECUTE"
      schema_privileges   = "USAGE"
      sequence_privileges = "SELECT,UPDATE"
      table_privileges    = "SELECT,INSERT,UPDATE,DELETE,TRIGGER"
    },
    readonly_user = {
      allow_iam_role_access = true
      schema_privileges     = "USAGE"
      sequence_privileges   = "SELECT"
      table_privileges      = "SELECT"
    },
    rw_user = {
      allow_iam_role_access = true
      database_privileges   = "CONNECT"
      routine_privileges    = "EXECUTE"
      schema_privileges     = "USAGE"
      sequence_privileges   = "SELECT"
      table_privileges      = "SELECT,UPDATE,INSERT,DELETE,TRIGGER"
    }
  }
  rds_postgres_user_default_privileges = {
    app_schema = [
      "app_unrestricted",
      "readonly_user",
      "rw_user",
    ],
  }
```

Please let me know if you can use this code or you want me to simplify it somehow (though in this case we won't test our exact use cases).

**Comment by talbx** [comment]
@cyrilgdn can you take another look 👀

**Comment by igor-nikiforov** [comment]
@cyrilgdn just a friendly reminder about this very import PR.

**Comment by talbx** [comment]
hey @cyrilgdn, are you alive 😅  ?

**Comment by talbx** [comment]
friendly reminder to take a look again @cyrilgdn.
This PR already celebrated its first birthday 🎂

File: postgresql/helpers.go [hunk 7]
```diff
@@ -267,6 +267,35 @@ func validatePrivileges(d *schema.ResourceData) error {
...
+		if p != "ALL" {
+			implicits = append(implicits, p)
+		}
+	}
+
+	s := make([]interface{}, len(implicits))
+	for i, privilege := range implicits {
+		s[i] = privilege
+	}
+	wantedSet := schema.NewSet(schema.HashString, s)
```
Comment (cyrilgdn) [inline postgresql/helpers.go:295]: I think this could be simplified to:
```suggestion
	implicits :=[]interface{}{}
	for _, p := range allowedPrivileges[objectType] {
		if p != "ALL" {
			implicits = append(implicits, p)
		}
	}
	wantedSet := schema.NewSet(schema.HashString, implicits)
```

File: postgresql/helpers_test.go [hunk 8]
```diff
@@ -45,3 +46,78 @@ func TestQuoteTableName(t *testing.T) {
 		})
 	}
 }
+
+func TestArePrivilegesEqual(t *testing.T) {
```
Comment (cyrilgdn) [inline postgresql/helpers_test.go:50]: Cool :+1:

File: postgresql/resource_postgresql_default_privileges.go [hunk 9]
```diff
@@ -268,8 +268,12 @@ func readRoleDefaultPrivileges(txn *sql.Tx, d *schema.ResourceData) error {
 	}
 
 	privilegesSet := pgArrayToSet(privileges)
-	d.Set("privileges", privilegesSet)
-	d.SetId(generateDefaultPrivilegesID(d))
+	privilegesEqual := resourcePrivilegesEqual(privilegesSet, d)
+
+	if !privilegesEqual {
+		d.Set("privileges", privilegesSet)
+		d.SetId(generateDefaultPrivilegesID(d))
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_default_privileges.go:275]: Why the `SetId` is in the `if`? It's not the case for `postgresql_grant` and I think we want to set it in any cases.

Currently this works anyway because the ID is based on fields that recreate the resource if they change so it will never change here, but this is still totally unrelated to privileges

File: postgresql/resource_postgresql_grant_test.go [hunk 10]
```diff
@@ -1139,6 +1139,83 @@ resource "postgresql_grant" "test" {
 	})
 }
 
+func TestAccPostgresqlImplicitGrants(t *testing.T) {
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant_test.go:1142]: :muscle:

**Review by cyrilgdn — COMMENTED** [review]
>  This PR already celebrated its first birthday 🎂

At 1yo I was still peeing on myself, this is quite young actually :trollface: 

Joke apart sorry for this huuuge delay again, with my work and personal life I have not much time for this project and each review takes hours :sweat_smile:

But I still try to come back from time to time to create new releases with community PRs.

Two small comment otherwise it seems good to me :+1: 
I promise to merge quickly after your fix 

> hey @cyrilgdn, are you alive 😅 ?

unless I die meanwhile :man_shrugging: 
I'd be careful with this kind of comment though, you don't know who is behind a nickname and what happen in their personal life :wink:

File: postgresql/resource_postgresql_default_privileges.go (hunk 9 above)
Comment (talbx) [reply postgresql/resource_postgresql_default_privileges.go]: you are right, this was probably just a slip.
changed this with [c35441d](https://github.com/cyrilgdn/terraform-provider-postgresql/pull/339/commits/c35441d539a2dc3b7e08bfa9ae5c0573cd53ec3f)

**Review by cyrilgdn — APPROVED** [review]
Thanks for your work :+1: , this will be released in v1.25 in the next days

**Comment by alamin-floenergy** [comment]
@cyrilgdn Can we please get a release soon with this changes?

**Comment by cyrilgdn** [comment]
@talbx @alamin-floenergy This has just been release in https://github.com/cyrilgdn/terraform-provider-postgresql/releases/tag/v1.25.0

**Comment by rhyek** [comment]
FWIW, I'm using 1.25.0 and still seeing the issue with this config:

```terraform
resource "random_password" "web_api_db_password" {
  length  = 32
  special = false
}

resource "postgresql_role" "web_api" {
  name     = "web_api"
  provider = postgresql.main
  login    = true
  password = random_password.web_api_db_password.result

  create_database = false
  create_role     = false
  superuser       = false
}

resource "postgresql_grant" "web_api_public_schema" {
  provider    = postgresql.main
  database    = aws_db_instance.postgresql.db_name
  role        = postgresql_role.web_api.name
  schema      = "public"
  object_type = "schema"
  privileges  = ["USAGE"]
}

resource "postgresql_grant" "web_api_public_tables" {
  provider    = postgresql.main
  database    = aws_db_instance.postgresql.db_name
  role        = postgresql_role.web_api.name
  schema      = "public"
  object_type = "table"
  privileges  = ["ALL"]
}

resource "postgresql_grant" "web_api_public_sequences" {
  provider    = postgresql.main
  database    = aws_db_instance.postgresql.db_name
  role        = postgresql_role.web_api.name
  schema      = "public"
  object_type = "sequence"
  privileges  = ["ALL"]
}

resource "postgresql_default_privileges" "web_api_tables_default" {
  provider    = postgresql.main
  database    = aws_db_instance.postgresql.db_name
  role        = postgresql_role.web_api.name
  schema      = "public"
  owner       = aws_db_instance.postgresql.username
  object_type = "table"
  privileges  = ["ALL"]
}

resource "postgresql_default_privileges" "web_api_sequences_default" {
  provider    = postgresql.main
  database    = aws_db_instance.postgresql.db_name
  role        = postgresql_role.web_api.name
  schema      = "public"
  owner       = aws_db_instance.postgresql.username
  object_type = "sequence"
  privileges  = ["ALL"]
}

```

```bash
Terraform will perform the following actions:

  # module.rds.postgresql_default_privileges.web_api_tables_default will be updated in-place
  ~ resource "postgresql_default_privileges" "web_api_tables_default" {
        id                = "web_api_c_prod_public_postgres_table"
      ~ privileges        = [
          - "DELETE",
          - "INSERT",
          - "MAINTAIN",
          - "REFERENCES",
          - "SELECT",
          - "TRIGGER",
          - "TRUNCATE",
          - "UPDATE",
          + "ALL",
        ]
        # (6 unchanged attributes hidden)
    }

  # module.rds.postgresql_grant.web_api_public_tables will be updated in-place
  ~ resource "postgresql_grant" "web_api_public_tables" {
        id                = "web_api_c_prod_public_table"
      ~ privileges        = [
          - "DELETE",
          - "INSERT",
          - "MAINTAIN",
          - "REFERENCES",
          - "SELECT",
          - "TRIGGER",
          - "TRUNCATE",
          - "UPDATE",
          + "ALL",
        ]
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

**Comment by amais33** [comment]
Thanks for your work on this!
I confirm that the issue is solved with postgres version under 17 for me.
But I still have the issue for "tables" with the version 17.
I think it's because of the new MAINTAIN privilege.
I found this 2 places where the list of tables privileges are present:
- [postgresql/helpers.go](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/25fbd1cc7c2697fe2da88272d3ef3a23e7fccf01/postgresql/helpers.go#L254)
- [postgresql/helpers_test.go](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/25fbd1cc7c2697fe2da88272d3ef3a23e7fccf01/postgresql/helpers_test.go#L74)

Maybe one need to add a test of postgres version and append the list with the MAINTAIN privilege if it's `=> 17`, WDYT?

**Comment by talbx** [comment]
> FWIW, I'm using 1.25.0 and still seeing the issue with this config:
> 
> ```hcl
> resource "random_password" "web_api_db_password" {
>   length  = 32
>   special = false
> }
> 
> resource "postgresql_role" "web_api" {
>   name     = "web_api"
>   provider = postgresql.main
>   login    = true
>   password = random_password.web_api_db_password.result
> 
>   create_database = false
>   create_role     = false
>   superuser       = false
> }
> 
> resource "postgresql_grant" "web_api_public_schema" {
>   provider    = postgresql.main
>   database    = aws_db_instance.postgresql.db_name
>   role        = postgresql_role.web_api.name
>   schema      = "public"
>   object_type = "schema"
>   privileges  = ["USAGE"]
> }
> 
> resource "postgresql_grant" "web_api_public_tables" {
>   provider    = postgresql.main
>   database    = aws_db_instance.postgresql.db_name
>   role        = postgresql_role.web_api.name
>   schema      = "public"
>   object_type = "table"
>   privileges  = ["ALL"]
> }
> 
> resource "postgresql_grant" "web_api_public_sequences" {
>   provider    = postgresql.main
>   database    = aws_db_instance.postgresql.db_name
>   role        = postgresql_role.web_api.name
>   schema      = "public"
>   object_type = "sequence"
>   privileges  = ["ALL"]
> }
> 
> resource "postgresql_default_privileges" "web_api_tables_default" {
>   provider    = postgresql.main
>   database    = aws_db_instance.postgresql.db_name
>   role        = postgresql_role.web_api.name
>   schema      = "public"
>   owner       = aws_db_instance.postgresql.username
>   object_type = "table"
>   privileges  = ["ALL"]
> }
> 
> resource "postgresql_default_privileges" "web_api_sequences_default" {
>   provider    = postgresql.main
>   database    = aws_db_instance.postgresql.db_name
>   role        = postgresql_role.web_api.name
>   schema      = "public"
>   owner       = aws_db_instance.postgresql.username
>   object_type = "sequence"
>   privileges  = ["ALL"]
> }
> ```
> 
> ```shell
> Terraform will perform the following actions:
> 
>   # module.rds.postgresql_default_privileges.web_api_tables_default will be updated in-place
>   ~ resource "postgresql_default_privileges" "web_api_tables_default" {
>         id                = "web_api_c_prod_public_postgres_table"
>       ~ privileges        = [
>           - "DELETE",
>           - "INSERT",
>           - "MAINTAIN",
>           - "REFERENCES",
>           - "SELECT",
>           - "TRIGGER",
>           - "TRUNCATE",
>           - "UPDATE",
>           + "ALL",
>         ]
>         # (6 unchanged attributes hidden)
>     }
> 
>   # module.rds.postgresql_grant.web_api_public_tables will be updated in-place
>   ~ resource "postgresql_grant" "web_api_public_tables" {
>         id                = "web_api_c_prod_public_table"
>       ~ privileges        = [
>           - "DELETE",
>           - "INSERT",
>           - "MAINTAIN",
>           - "REFERENCES",
>           - "SELECT",
>           - "TRIGGER",
>           - "TRUNCATE",
>           - "UPDATE",
>           + "ALL",
>         ]
>         # (5 unchanged attributes hidden)
>     }
> 
> Plan: 0 to add, 2 to change, 0 to destroy.
> ```

@rhyek I think there is a slight misunderstanding in the fix within this PR.
First of all, I can reproduce the behaviour you pointed out. Second, this is indeed not covered by the implementation, but it actually wasn't in scope. This PR is about once you set "ALL" and apply it, on the next `terraform plan` it should not have any changes planned. 

But I understand your issue and will take a closer look at it.
