### PR TITLE
Fix getting stuck on refreshing postgresql grant

### LINKED ISSUE #335: terraform refresh gets stuck forever on postgresql_grant schema under certain conditions
### Terraform Version
```
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.20.0
+ provider registry.terraform.io/hashicorp/aws v4.66.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Affected Resource(s)
- resource_postgresql_grant (only object_type schema is affected)

### Terraform Configuration Files
```hcl
provider "postgresql" {
  host      = "RDS_HOST_URI"
  port      = 5432
  database  = "postgres"
  username  = "postgres"
  password  = "SECRET"
  sslmode   = "require"
  superuser = false
  max_connections = 1
}

resource "postgresql_grant" "postgres_public_schema_revoke_all_from_public" { 
  database    = "postgres"
  schema      = "public"
  role        = "public"
  object_type = "schema"
  privileges  = []
}
```

### Expected Behavior
- `terraform refresh` should not get stuck
- irrelevant to this particular issue, but I'd expect the provider to timeout not only when establishing a connection but also during a transaction

### Actual Behavior
`terraform refresh` gets stuck at `postgresql_grant schema` in ~80% of runs

### Steps to Reproduce
1. Create an RDS instance (PostgreSQL 14.7) (Note: I was not able to reproduce the issue on local machine)
2. Expose RDS instance to internet by means of AWS Load Balancer
3. Apply the configs
    ```
    terraform apply
    ```
4. And then run several times (`--lock=false` is to avoid need in unlocking every time it gets stuck, `--parallelism=1` is to eliminate possible side effects of parallelism)
    ```
    terraform refresh --lock=false --parallelism=1
    ```

### Important Factoids
1. I'm able to reproduce this issue quite reliably on RDS and I'm not able to reproduce this on local
2. The issue happens only when database for initial connection (configured in provider) is the same as the one `postgresql_grant` is applied to (`postgres` and `postgres` in this case but this happens to any other database as long as both are the same), in this case connection to the database is [reused](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/b33fe397a96a9bd57ce5856f8247812b0ab8c983/postgresql/helpers.go#L337)
3. The issue happens only when the `object_type` is `schema`
4. The provider gets stuck at [startTransaction()](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/fea83f376887d76424148b665b47c7f5c72371cc/postgresql/resource_postgresql_grant.go#L737) and more specifically at [db.Begin()](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/helpers.go#L345) when a new transaction starts without previous transaction finished
5. With all preconditions mentioned above the provider gets stuck in around 80% of runs.

### PR DESCRIPTION
**Pull request by giner**
This change fixes terraform refresh getting stuck forever on postgresql_grant schema when provider connection database is the same as the one we are trying to read schema information from. Until now the issue could be reproduced only on RDS (PostgreSQL 14.7). Fixed by explicitly finishing one transaction before starting a new one.

Fixes #335

### CODE REVIEW

**Review by pagalba-com — APPROVED** [review]

**Comment by pagalba-com** [comment]
I can confirm that this fixed issue with stuck terraform refresh on aws rds PostgreSQL v14.7.

Compiled binary from MR branch ant it works as expected. It should go main stream.

**Review by pagalba-com — APPROVED** [review]
I can confirm that this fixed issue with stuck terraform refresh on aws rds PostgreSQL v14.7.

Compiled binary from MR branch ant it works as expected. It should go main stream.

**Comment by pagalba-com** [comment]
@cyrilgdn please approve this MR! Its impossible to work on aws prod without this.

**Comment by giner** [comment]
@kylejohnson would you take a look at this fix please?

File: postgresql/resource_postgresql_grant.go [hunk 1]
```diff
@@ -730,6 +730,8 @@ func checkRoleDBSchemaExists(client *Client, d *schema.ResourceData) (bool, erro
 		return false, nil
 	}
 
+	deferredRollback(txn)
```
Comment (cyrilgdn) [inline postgresql/resource_postgresql_grant.go:733]: I think we should better avoid creating a new transaction and use the existing one if it's the same database.

So line 738:

```go
var dbTxn *sql.Tx
if database == client.databaseName {
  dbTxn = txn
} else {
	var err error;
	dbTxn, err := startTransaction(client, database)
	if err != nil {
		return false, err
	}
	defer deferredRollback(dbTxn)
}
```

(and actually if it's for another database a transaction is not really needed as it executes only 1 request but I don't think we already have an helper to get a simple DB connection for alternative DB)

What do you think?

**Review by cyrilgdn — COMMENTED** [review]
Hi @giner ,

Thanks for opening this PR and sorry for the delay

I've added one comment, let me know what do you think about it.

File: postgresql/resource_postgresql_grant.go (hunk 1 above)
Comment (giner) [reply postgresql/resource_postgresql_grant.go]: Makes sense to me. I'll unify this function to be more in line with the rest of the code.

**Review by cyrilgdn — APPROVED** [review]
Thanks :tada:

**Comment by giner** [comment]
@cyrilgdn, Does anything need to be done for v1.22.0 to hit the registry? It's not there yet.
